import Image from "next/image";
import React from "react";
import { Button } from "../ui/button";
import Link from "next/link";

export default function FeaturedCategories() {
  const categories = [
    {
      title: "Prebuilt Gaming PCs",
      image:
        "https://www.cyberpowerpc.com/ti/home/Homepage_Subfeature_Prebuilt.jpg",
      description:
        "Browse thousands of PC builds generated by users showing their part list, photos and overall build experience.",
      link: "/system/Prebuilt-Gaming-PC-GLX-99622",
    },
    {
      title: "Custom Gaming PCs",
      image:
        "https://www.cyberpowerpc.com/ti/home/Homepage_Subfeature_Custom.jpg",
      description:
        "Browse thousands of PC builds generated by users showing their part list, photos and overall build experience.",
      link: "/system/Prebuilt-Gaming-PC-GLX-99622",
    },
    {
      title: "Laptops",
      image:
        "https://www.cyberpowerpc.com/ti/home/Homepage_Subfeature_Laptop.jpg",
      description:
        "Browse thousands of PC builds generated by users showing their part list, photos and overall build experience.",
      link: "/system/Prebuilt-Gaming-PC-GLX-99622",
    },
    {
      title: "Monitors",
      image:
        "https://www.cyberpowerpc.com/ti/home/Homepage_Subfeature_Monitor.jpg",
      description:
        "Browse thousands of PC builds generated by users showing their part list, photos and overall build experience.",
      link: "/system/Prebuilt-Gaming-PC-GLX-99622",
    },
  ];

  return (
    <div className="grid lg:grid-cols-2 space-x-2 space-y-2">
      <div className="space-y-2">
        <div className="relative">
          <Image
            src="https://www.cyberpowerpc.com/ti/home/Homepage_Subfeature_Prebuilt.jpg"
            alt="Prebuilt Gaming PC GLX 99622"
            height={800}
            width={800}
            className="h-full w-full"
          />
          <div className="absolute z-30   top-[10%] text-center text-white w-full">
            <h3 className="text-2xl md:text-4xl font-bold text-white">
              PreBuilt Gaming PCs
            </h3>
            <p className="mt-2 text-md md:text-lg max-w-md mx-auto">
              Experience top-tier gaming with our prebuilt PCs, designed for
              speed and graphics without the build hassle.
            </p>
            <Button asChild className="mt-8" variant="secondary">
              <Link href="/system" className="">
                Buy Now
              </Link>
            </Button>
          </div>
        </div>
        <div className="flex max-sm:flex-col lg:flex-col xl:flex-row space-y-4 space-x-4 items-center bg-gray-100 p-10">
          <Image
            src="https://www.cyberpowerpc.com/template/common/images/promo/Laptop_Tracer_350x350.png"
            alt="Prebuilt Gaming PC GLX 99622"
            height={800}
            width={800}
            className="h-[220px] w-[220px]"
          />
          <div className="px-4 ">
            <h3 className="text-4xl font-bold">Performance Workstations</h3>
            <p className="text-md text-gray-600">
              Efficiently power through applications with our high-performance
              workstations, ideal for graphics rendering and scientific
              computing.
            </p>
            <Button asChild className="mt-8">
              <Link href="/system/Prebuilt-Gaming-PC-GLX-99622">Shop Now</Link>
            </Button>
          </div>
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex max-sm:flex-col lg:flex-col xl:flex-row space-y-4 space-x-4 items-center bg-gray-100 p-10">
          <Image
            src="https://www.cyberpowerpc.com/images/hd/HD-403-151_200.png"
            alt="Prebuilt Gaming PC GLX 99622"
            height={800}
            width={800}
            className="h-[220px] w-[220px]"
          />
          <div className="px-4">
            <h3 className="text-4xl font-bold">Free</h3>
            <p className="text-md text-gray-600">
              4TB 5400 RPM Hard Drive with Single SSD Purchase for all Desktops
              [Excludes Prebuilt PC]
            </p>
            <Button asChild className="mt-8">
              <Link href="/system/Prebuilt-Gaming-PC-GLX-99622">Shop Now</Link>
            </Button>
          </div>
        </div>
        <div className="relative">
          <Image
            src="https://www.cyberpowerpc.com/ti/home/Homepage_Subfeature_Gaming_PCs.jpg"
            alt="Prebuilt Gaming PC GLX 99622"
            height={800}
            width={800}
            className="h-full w-full"
          />
          <div className="absolute z-30   top-[10%] text-center text-white w-full">
            <h3 className="text-2xl md:text-4xl font-bold text-white">
              Completed Build PCs
            </h3>
            <p className="mt-2 text-md md:text-lg max-w-md mx-auto">
              Browse thousands of PC builds generated by users showing their
              part list, photos and overall build experience.
            </p>
            <Button asChild className="mt-8" variant="secondary">
              <Link href="/system" className="">
                Buy Now
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
